### ISSUE TITLE
US 5

### ISSUE THREAD

**Issue by KilianBau** [KilianBau/capstone-project#13]
## Value proposition

As a travel enthusiast 
I want to have a navigation and a favourite button   
so that I am able to get to the favourite page and favour the countries.  

## Description
<img width="471" alt="Screenshot 2023-08-18 at 09 10 51" src="https://github.com/KilianBau/capstone-project/assets/137038489/19670eff-ef44-4b4f-bb77-176621721638">

## Acceptance criteria

- [ ] create the favourite button 
- [ ] it should be visible next to the country name
- [ ] create a nav bar with two options to click  
- [ ] create the favourite page that shows the favourite countries
- [ ] you can enter this page by clicking the heart icon at the nav bar

## Tasks

- [ ] create a branch "feat/favourite-button-and-page"
- [ ] create the favourite button component with a heart icon 
- [ ] add it to the country list page
- [ ] at _app.js write a function to toggle the favourite button (array-methods find and map, and new key isFavourite) 
- [ ] create the favourite page that displays the favourite country cards with the filled heart 
- [ ] create the nav bar component
- [ ] create a nav bar with the home page link and the favourite page link (home icon and heart icon) 
- [ ] add the nav bar component to the country list page and to the favourite page

**Comment by jonas8900** [comment]
looks like you use the british version of favorite :D! i would switch the last sentence of your value proposition > so that I am able to favour the countries and see them on the favourite page. So you make clear that you can see the favorites you clicked on, on the favorite page. 

very good acceptance criteria ! 

Good idea to do a globalstate here on the _app.js. 

short trick, youi do not need to add the nav bar component to each pages, add the navigation to the _app.js so you get the navbar on every page!

**Comment by KilianBau** [comment]
Thank you for the good review and the trick!
