### ISSUE TITLE
US 6

### ISSUE THREAD

**Issue by KilianBau** [KilianBau/capstone-project#14]
## Value proposition

As a travel enthusiast 
I want to upload my travel pictures   
so that I am able to see the best pictures of my journey sorted by the country I visited .

## Description
<img width="550" alt="Screenshot 2023-08-18 at 11 28 42" src="https://github.com/KilianBau/capstone-project/assets/137038489/48340bb3-70eb-43c6-9af5-4cdb0b8f199c">

## Acceptance criteria

- [ ] implement the upload image button in the form of the adding country page 
- [ ] it should be a button in an elipses form 
- [ ] the uploaded images should be shown on the detail country page
- [ ] two in a row 
- [ ] on the detail country page the country and the time periode is displayed at the top   
- [ ] the scroll behavior is vertical 

## Tasks

- [ ] create a branch "feat/upload-images"
- [ ] create the upload img button in the country form component    
- [ ] create the handleUploadImg function in the _app.js file  
- [ ] this function should be triggered with the upload img button in the country form component  
- [ ] the onSubmit function sets the new state and the pictures should be shown on the detail country page

**Comment by NicoleHoerner** [comment]
Nice feature! Pictures are always great!😃
