### ISSUE TITLE
US 7

### ISSUE THREAD

**Issue by KilianBau** [KilianBau/capstone-project#15]
## Value proposition

As a travel enthusiast 
I want to comment my pictures and have a detail view of it    
so that I am able to see one picture and add a comment.   

## Description

<img width="452" alt="Screenshot 2023-08-18 at 15 31 17" src="https://github.com/KilianBau/capstone-project/assets/137038489/6a788ae2-6104-404d-ab74-6ea3a43efee8">

## Acceptance criteria

- [ ] create the detail picture view page 
- [ ] the picture you clicked on should be shown  
- [ ] it should be possible to delete the picture 
- [ ] it should be possible to write and edit a comment for this picture 
- [ ] there should be a go back button that links to the detail country page 

## Tasks

- [ ] create a branch "feat/detail-picture-view"
- [ ] create the detail picture view page and a component for it     
- [ ] put in the go back button component on the detail picture view page 
- [ ] write a function in _app.js for the delete button (filter method, compare the id, return false or true, set new state)   
- [ ] display the chosen picture  (array-method map and id)
- [ ] create in the detail picture view component a form with label and input field for the comment (onChange of the input field a 
       new state should be set: in the chosen picture object new key=comment with value ) 
- [ ] paste the comment in the detail country page component  (map-method)  
- [ ] implement a link for each picture which links to the detail picture view (Link)

**Comment by F-Kirchhoff** [comment]
Please refactor this into 3 user stories:
- detail view only
- delete functionality
- comments

**Comment by F-Kirchhoff** [comment]
LGTM 👍
