### ISSUE TITLE
US 8

### ISSUE THREAD

**Issue by KilianBau** [KilianBau/capstone-project#16]
## Value proposition

As a travel enthusiast 
I want to delete individual pictures    
so that I am able to remove bad pictures.   

## Description

<img width="166" alt="Screenshot 2023-08-18 at 16 05 53" src="https://github.com/KilianBau/capstone-project/assets/137038489/41c6f733-ba62-493f-b1db-a4ea83472409">

## Acceptance criteria

- [ ] next to the go back button should be the delete button  
- [ ] the picture you clicked on should be deleted by clicking the delete button  

## Tasks

- [ ] create a branch "feat/picture-delete-button"
- [ ] in the detail picture view component create a button witch a red x icon
- [ ] onClick the button should handle the delete function    
- [ ] write the delete function in _app.js (filter method, compare the id, return false or true, set new state)

**Comment by jonas8900** [comment]
this user story looks very ordered and short! I like that a lot :). But do you really need a global state for the delete function, or you just need it on one page? 

maybe you could think about that, but in my opinion it isn't a mistake, but could safe you a bit more time than drill the props through the components.
