### ISSUE TITLE
US 9

### ISSUE THREAD

**Issue by KilianBau** [KilianBau/capstone-project#17]
## Value proposition

As a travel enthusiast 
I want to add and edit comments of my pictures    
so that I am able to see the comments under the pictures.    

## Description

<img width="440" alt="Screenshot 2023-08-18 at 16 14 41" src="https://github.com/KilianBau/capstone-project/assets/137038489/fc653907-7a0b-4c0e-b893-935b25ba3af4">

## Acceptance criteria

- [ ] it should be possible to write and edit a comment 
- [ ] there should be a comment input field at the detail picture view   
- [ ] the comment should be displayed at the detail country page 

## Tasks

- [ ] create a branch "feat/comments-for-the-pictures"
- [ ] create in the detail picture view component a form with label and input field for the comment (onChange a new state
      should be set: in the chosen picture object new key=comment with value ) 
- [ ] paste the comment in the detail country page component (map-method)

**Comment by jonas8900** [comment]
i like your value proposition ! When i go through your acceptance criteria i think there should be a bit more information about the comment because, when i look at your description i dont see an inputfield, i only see a field with "Kommentar", is this a placeholder or does this button shows me all comments of this picture? 

maybe you can formulate your task a bit more detailed, this can be very helpful when you go into the coding phase, because i think you need a function to add's and to change the comments after you added one, maybe you could write this in your tasks.

**Comment by KilianBau** [comment]
Yes you are right, I changed it. Thank you for the review!
