### ISSUE TITLE
US 9

### ISSUE THREAD

**Issue by KilianBau** [KilianBau/capstone-project#23]
## Value proposition

As a travel enthusiast 
I want to edit the country name and the date    
so that I am able to change the name and date    

## Description

![Screenshot 2023-08-29 at 12 27 39](https://github.com/KilianBau/capstone-project/assets/137038489/d31f0d9e-0b0a-4f57-b71c-e92b67eaa351)

## Acceptance criteria

- [ ] the edit button should be visible next to the country name  
- [ ] on click the edit page should be displayed   
- [ ] the input fields have the value of the before inputted country and dates 
- [ ] the end date can't be before the start date 

## Tasks

- [ ] create a branch "feat/edit-country-details"
- [ ] create a component for the edit page with a form and two input fields and a "Bestätigen" button
- [ ] onSubmit the state should be updated 
- [ ] implement the date picker and a function that prevents that the end date can be picked before the start date  
- [ ] create the edit page 
- [ ] add the component to the edit page

**Comment by JanaS87** [comment]
Looks good 👍
