### ISSUE TITLE
US 10

### ISSUE THREAD

**Issue by KilianBau** [KilianBau/capstone-project#25]
## Value proposition

As a travel enthusiast 
I want to upload more pictures to the country    
so that I am able to extend the gallery     

## Description
<img width="252" alt="Screenshot 2023-08-30 at 16 01 14" src="https://github.com/KilianBau/capstone-project/assets/137038489/3b29ce15-9474-411d-ad2e-e0b38ff6cc59">

## Acceptance criteria

- [ ] the upload button should be above the country name   
- [ ] on click the cloudinary upload page should be opened    
- [ ] you can make multiple uploads 
- [ ] the uploads should be display below the others 

## Tasks

- [ ] create a branch "feat/upload-img-country-details"
- [ ] add the cloudinary upload button component to the country details page component
- [ ] onUpload the state should be updated with the new uploaded pictures
- [ ] make sure that they are displayed blow the other pictures on this page
