### ISSUE TITLE
US 11

### ISSUE THREAD

**Issue by KilianBau** [KilianBau/capstone-project#28]
## Value proposition

As a travel enthusiast 
I want to have a nice styled app    
so that I am happy to use it.     

## Acceptance criteria

- [ ] a simple design with just three colors    
- [ ] a new app logo that goes well with the other design     

## Tasks

- [ ] create a branch "feat/app-design"
- [ ] update the styling and the app name design
