### ISSUE TITLE
US 12

### ISSUE THREAD

**Issue by KilianBau** [KilianBau/capstone-project#29]
## Value proposition

As a travel enthusiast 
I want to have an app without bugs     
so that I am able to use it.     

## Acceptance criteria

- [ ] by adding a picture to a gallery, the already added pictures should still be shown in the fullscreen
- [ ] when something went wrong there should be an error message and it should be possible to go back to the last page   

## Tasks

- [ ] create a branch "feat/debugging "
- [ ] update the function for the adding image component
- [ ] implement the error handling for everything that could go wrong

**Comment by chris-kuehn** [comment]
Sounds like a plan! :)
