### ISSUE TITLE
US 3

### ISSUE THREAD

**Issue by KilianBau** [KilianBau/capstone-project#3]
## Value proposition

As a travel enthusiast 
I want to add the time period I visited the country  
so that I am able to see more details about my past trip.

## Description

<img width="850" alt="Screenshot 2023-08-14 at 14 28 47" src="https://github.com/KilianBau/capstone-project/assets/137038489/75f0d900-eae1-4caf-aad4-65f622122c10">

## Acceptance criteria

- [ ] create the detail page of the country 
- [ ] you can get on this page by clicking on the country name at the country list page 
- [ ] the app name is visible at the top in an elipses form with red background 
- [ ] there is a card with the country name and the time period of the visit 
- [ ] add an time period input field to the adding country page that you can pick
    the arrival and departure date 

## Tasks

- [ ] create a branch "feat/country-detail-page"
- [ ] create the detail country page 
- [ ] display the country name and the time period with the array method map and the id 
- [ ] add the app name component to the top of the country page
- [ ] expand the adding page with a label and input field for the dates and make it required 
- [ ] add the input to the country array with an unique id by using useState and UID 
- [ ] add the link for the detail page to the countries

**Comment by Roland-Hufnagel** [comment]
LGTM, but as I see it the first time it is hard to understand. I would prefer some arrows on your wireframe, e.g. one coming from the ``+`` button leading to the third frame. And one coming from ``Bestätigen`` leading to the second frame (or to the first - as you would like)

**Comment by KilianBau** [comment]
okay I get it, will include it in my next US 👍
