### ISSUE TITLE
US13

### ISSUE THREAD

**Issue by KilianBau** [KilianBau/capstone-project#32]
## Value proposition

As a travel enthusiast 
I want to have a loading screen while the pictures are loading     
so that I have a feedback that something is progressing.   

## Description

<img width="589" alt="Screenshot 2023-09-07 at 10 52 39" src="https://github.com/KilianBau/capstone-project/assets/137038489/1eaffd23-0053-430d-b16d-08189a571469">

## Acceptance criteria

- [ ] the loading message should be displayed so that the pictures are able to load in the background 
- [ ] after the loading message the pictures should be shown  

## Tasks

- [ ] create a branch "feat/loadingMessage "
- [ ] implement a function at the detail country page that shows a loading message for a few seconds
