### ISSUE TITLE
US 4

### ISSUE THREAD

**Issue by KilianBau** [KilianBau/capstone-project#7]
## Value proposition

As a travel enthusiast 
I want to delete a added country and have a go back button  
so that I am able to fix a mistake and have a better navigation.

## Description

<img width="613" alt="Screenshot 2023-08-16 at 16 12 27" src="https://github.com/KilianBau/capstone-project/assets/137038489/2f95ec8d-d0a0-4a7b-99f3-f04c2d2e025f">

## Acceptance criteria

- [ ] create the delete and the go back button 
- [ ] both should be visible at the top of the detail country page
- [ ] the go back button should also be visible at the top of the adding country page
- [ ] the app name is visible at the top in an elipses form with red background 
- [ ] you should have the choice to confirm or cancel the delete with two buttons
- [ ] the delete button should show a pop up page to confirm or cancel the removal of a country from the list  
- [ ] by clicking the go back button you should be navigated to the previous page

## Tasks

- [ ] create a branch "feat/delete-and-back-button"
- [ ] create a component for the go back button 
- [ ] it should link to the country list page (Link)
- [ ] insert the icon 
- [ ] add a small styling
- [ ] add the go back button component to the card and form pages 
- [ ] it should be visible at the left top of each page 
- [ ] create a delete button on the detail country page
- [ ] insert the icon and wrap the button around it
- [ ] add a small styling 
- [ ] create a pop up page that should be shown after clicking the delete button (dialog element) 
- [ ] write the function for the two buttons (confirm button: carry out the delete function; cancel button: link back to the 
detail country page) 
- [ ] create the function to delete the chosen country (filter method, compare the id, return false or true, set new state)

**Comment by CJAkkuec** [comment]
The tasks are a bit verbose, but that's not necessarily a bad thing. I prefer that over one checkbox stating "do the thing".
As a sidenote: you may want to consider a sort of dialogue before deleting something so the user can confirm that they're sure. 👍

**Comment by KilianBau** [comment]
That's a good idea thank you :)

**Comment by CJAkkuec** [comment]
>  create a pop up page that should be shown after clicking the delete button (p-tag with true or false query)
Hint: That's a modal featuring the `<dialog>` [element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) 👀
